### ISSUE TITLE
What's the purpose of all of `:-` symbols in README?

### ISSUE THREAD

**Issue by boholder** [minecraft-access/minecraft-access#125]
Like `Keybindings and combinations:-` or `Configuration Options:-`, do them serve a special purpose? @khanshoaib3

**Comment by khanshoaib3** [comment]
It's just a decorative thing that I do with headings, nothing special 🙃

**Comment by boholder** [comment]
> It's just a decorative thing that I do with headings, nothing special 🙃

Ok, so... I'll delete them and replace them with markdown heading `###` for better screen reader navigation?
