### ISSUE TITLE
Sharable structure blue print file

### ISSUE THREAD

**Issue by boholder** [minecraft-access/minecraft-access#176]
So... building is a trouble for visually impaired players. This is mainly because tutorial videos and articles tend to use images rather than words to describe the steps of building.

How about make a new feature for this:

1. Set two points (like resident mod, set two points with wood axe), then the mod will record information of every blocks inside the 3D zone into a json file.
2. Share the file with other players, put the file under somewhere.
3. Load the file into the game by set only the first point, then the mod will regard the zone as a construction area and speak extra information like "Expect {block info in file}, But ...", "Correct, ...".

Different languages are a problem for record format. This feature can be considered only after there are enough stable and experienced players.

**Comment by khanshoaib3** [comment]
There are also mods that build pre-designed structures like houses, farms, etc.
Here's one- [prefab](https://www.curseforge.com/minecraft/mc-mods/prefab)
