### ISSUE TITLE
Can't press Tab to speak online players

### ISSUE THREAD

**Issue by boholder** [minecraft-access/minecraft-access#185]
By 大地战神 from Discord:

> I am still playing version 1.19.3. 
> ... 
> the tab key doesn't announce the currently online players, which is quite bothersome. 
> I always have to press 'P' to open the social menu and use OCR to find out the number and names of the current players.

Sorry for bothering @khanshoaib3, but does this mod has this feature? I didn't aware of it when I improved the manual (by reading the code file one by one)...

**Comment by khanshoaib3** [comment]
It's not a feature of the mod rather the game.
AFAIK, pressing tab brings up a kind of overlay on the hud screen with list of five or so online players. The social menu must be something similar. I don't remember patching it though.

**Comment by boholder** [comment]
> It's not a feature of the mod rather the game. AFAIK, pressing tab brings up a kind of overlay on the hud screen with list of five or so online players. The social menu must be something similar. I don't remember patching it though.

Ahhh... now I have some memories, thanks.
