### ISSUE TITLE
Chat Screen? Read one character at left of the cursor position whie moving the cursor

### ISSUE THREAD

**Issue by boholder** [minecraft-access/minecraft-access#187]
By 千夜 from QQ.

This will help player modify their sentences and commands on fly, right in this input field.
Currently they had to copy the text to some other editors to check and modify it.
Hope this is an easy implementation that can be done by adding some code in `ChatScreenMixin`

BTW, is the pressing number 0~9 to speak chat message still works? @khanshoaib3  I haven't figured out how to trigger it.

https://github.com/khanshoaib3/minecraft-access/blob/758f3b3236bba10ff54a3130c8cff2a510b8875c/common/src/main/java/com/github/khanshoaib3/minecraft_access/mixin/ChatScreenMixin.java#L45-L76

**Comment by khanshoaib3** [comment]
@boholder I think it is alt + number keys to read the previous chats.

**Comment by boholder** [comment]
> @boholder I think it is alt + number keys to read the previous chats.

Thanks! Will add it into the manual right away. Can you help on checking if some exist features isn't in the manual BTW? @khanshoaib3 
https://github.com/khanshoaib3/minecraft-access/blob/1.20/doc/FEATURES.md
