### ISSUE TITLE
crash on world startup

### ISSUE THREAD

**Issue by Karrtaan** [minecraft-access/minecraft-access#25]
Whenever I try to open a newly created world, minecraft throws a java.lang.NoSuchMethodError. The world itself is fully loading, but after that, it crashes without any player interaction, a crash report is attached.
[crash-2023-04-30_13.44.12-client.txt](https://github.com/khanshoaib3/minecraft-access/files/11361980/crash-2023-04-30_13.44.12-client.txt)

**Comment by khanshoaib3** [comment]
Looks like you're using 1.19.4
The mod is only compatible with 1.19.3 at the moment.
