### ISSUE TITLE
Forces Cursor to Reset to Top Left Corner

### ISSUE THREAD

**Issue by RoseTintDag** [minecraft-access/minecraft-access#276]
**Modloader:** Neoforge (Also tried with Forge)
**Modloader Version:** 47.1.101 (Forge: 47.2.0)

**Minecraft Version:** 1.20.1

**Scenario:** I had a few mods installed when I narrowed down the problem, but I also tried with just Minecraft Access + Architectury

**Issue:** The cursor hard resets to the top left of the screen whenever you change menus. Some (sub)menu changes don't trigger this bug, but it is persistent through every different menu

**Context**: I am a sighted player, but I wish to include this mod in my modpack for any players with low vision. The hard reset is very jarring and it interrupts gameplay for sighted players

I'll have to take it out the pack for now, but I hope it'll be patched before I release the modpack

Thanks for your hard work!

**Comment by boholder** [comment]
This class should be blamed for your issue:

https://github.com/khanshoaib3/minecraft-access/blob/b3852294cacac28ad2707c39c5d8cd2bd7e6485c/common/src/main/java/com/github/khanshoaib3/minecraft_access/features/MenuFix.java#L23-L30

And you can close this feature by closing "Enable Menu Fix" configuration.
https://github.com/search?q=repo%3Akhanshoaib3/minecraft-access%20menuFixEnabled&type=code

---

Some more:
1. This mod isn't support NeoForge right now, and I haven't following the diff between MinecraftForge and NeoForge so I don't know if this mod works normally on NeoForge.
2. I wonder how your mod make use of this mod and what else modification we can make for you.

**Comment by RoseTintDag** [comment]
Thank you for that! I disabled it in the config menu, and I'll try it on my next playtest.

re: NeoForge vs Forge, so far there is no or few technical differences between NeoForge and Forge. I've heard that mods for either loader can work on either loader..... for now. Emphasis on the "for now". The team plans to change more to the code, over time. 

re: I'll be doing my best to make the modpack page accessible for screen-readers, and hopefully including a guide on how to get started with Minecraft Access. I'll let you know if I need anything else, but this has been super helpful already!
