### ISSUE TITLE
Inventory Control: Speak mouse hovered item

### ISSUE THREAD

**Issue by boholder** [minecraft-access/minecraft-access#281]
while keeping keyboard cursor moving feature in Inventory Control.

**Comment by boholder** [comment]
https://github.com/accessible-minecraft/accessibility-plus-extended/blob/master/Accessibility%20Plus%20Extended%2Fsrc%2Fmain%2Fjava%2Fnet%2Fshoaibkhan%2Faccessibiltyplusextended%2Fmixin%2FItemStackTooltipInject.java

**Comment by khanshoaib3** [comment]
Refer to the commits in the `hovered_tooltip` branch.
