### ISSUE TITLE
Directional sound test

### ISSUE THREAD

**Issue by Jookia** [minecraft-access/minecraft-access#309]
I have a friend that recently tried this mod who is both fully blind and fully deaf in one ear, so stereo effects don't work very well. It's my understanding that having some kind of pitch system that tells you which left/right direction to look could help. Maybe there could be a way to switch which direction the pitch system uses with a button, and lock the mouse to an axis? Or maybe it could use a different wave?

**Comment by boholder** [comment]
Once https://github.com/khanshoaib3/minecraft-access/issues/153 is implemented, then we'll have a surrounding sound cue system, then this feature can be under consideration easily.
And... this mod will speak direction while player's head turning, can that feature helps your friend?
https://github.com/khanshoaib3/minecraft-access/blob/1.21/doc/FEATURES.md#camera-controls
https://github.com/khanshoaib3/minecraft-access/blob/1.21/doc/GOOD_RESOURCES.md#game-control

**Comment by Jookia** [comment]
Thanks for the response!

Yes it says the direction they're facing, but they don't know what to do with
that information.

**Comment by boholder** [comment]
> they don't know what to do with that information.

There are text and video guides in links, hope those help your friend.
(And... do you know some Java devs that might willing to implement this feature or this mod?)

**Comment by Jookia** [comment]
I did some more looking at the guides and links and found of they couldn't hear
footsteps. Installing the footsteps mod fixed that.

I don't know any Java devs that would be able to help here, sorry.

**Comment by boholder** [comment]
Intro: play a series of directional sound cues with speaking the direction, for checking... whatever, for checking something.

**Comment by Jookia** [comment]
Uh, just an update but my friend gave up on playing Minecraft as it couldn't figure out the direction of objects, so I'm not interested in this issue any more

Aug 5, 2024 23:48:04 boholder ***@***.***>:

**Comment by boholder** [comment]
Ok...sadly to hear that. Maybe your friend would like to play stardew? with stardew-access mod.
