### ISSUE TITLE
Support Jade as an alternative block narration backend

### ISSUE THREAD

**Issue by sgmedev** [minecraft-access/minecraft-access#325]
[Jade](https://modrinth.com/mod/jade) shows information about the currently targeted block including container contents and I18N and has a binding for the narrator to read this information aloud.

Currently to use Jade's TTS you have to either press the TTS button to read once or set the TTS button to be a toggle in the config  to read automatically however this currently conflicts with MC Access and prevents using the TTS button to read on demand. Using the toggle also makes it easy to accidentally disable leaving the user with nothing.

A Jade integration would have MC Access call Jade's TTS method if Jade is detected instead of using our own implementation providing a much more detailed description.

A config option may be desired for users who like the current terse reading but want to use Jade's TTS key for on-demand details

Jade's TTS method:
https://github.com/Snownee/Jade/blob/380842dd425f3e252b51dbe52070b7889725ac84/src/main/java/snownee/jade/overlay/WailaTickHandler.java#L58-L76

And where it is called when using the TTS key:
https://github.com/Snownee/Jade/blob/380842dd425f3e252b51dbe52070b7889725ac84/src/main/java/snownee/jade/JadeClient.java#L150

CC: @braillebennett

**Comment by boholder** [comment]
I mistaken this issue's purpose in discord, this is the code you'd like to modify <https://github.com/khanshoaib3/minecraft-access/blob/1.21/common/src/main/java/com/github/khanshoaib3/minecraft_access/features/ReadCrosshair.java>
