### ISSUE TITLE
AnimatedResultButtonMixin's behavior

### ISSUE THREAD

**Issue by boholder** [minecraft-access/minecraft-access#33]
https://github.com/khanshoaib3/minecraft-access/blob/8e1e3bd874d33c10dd56708883547cc81b7bd4b8/common/src/main/java/com/github/khanshoaib3/minecraft_access/mixin/AnimatedResultButtonMixin.java#L12-L25

Will speak "craftable / not craftable {number} {item}", but would not automatically speak when anime changes to next option. 
You need to keep clicking to trigger the narration.

**Comment by khanshoaib3** [comment]
This is a known issue, fixing it may require rewriting other parts as well, will look into this later.

**Comment by boholder** [comment]
You mean THIS issue, right?
https://github.com/khanshoaib3/minecraft-access/pull/32#issuecomment-1564690988

**Comment by khanshoaib3** [comment]
yup
