### ISSUE TITLE
Documentation should more clearly mention that this repository has a submodule

### ISSUE THREAD

**Issue by emassey0135** [minecraft-access/minecraft-access#332]
CONTRIBUTING.md mentions that minecraft-access-i18n is a Git submodule in the "File Structure" section, but I think this fact should also be mentioned under "Setting up Local Environment". If you clone the project without the "--recurse-submodules" option and run "./gradlew build", the project builds without errors, but when you run the compiled mod, the string identifiers are spoken instead of the localized version of the string. This was confusing for me when I tried to compile the mod for the first time.

**Comment by boholder** [comment]
You're right, will do it.

**Comment by boholder** [comment]
Close this issue since the I18N repo has been merged into (this) main repo by #353
