### ISSUE TITLE
What's "FIXME && Config.get(Config.getHelditemnarratorkey())" purpose?

### ISSUE THREAD

**Issue by boholder** [minecraft-access/minecraft-access#36]
https://github.com/khanshoaib3/minecraft-access/blob/86b33fb1a372d512e10eb9fd651a0508c52904bc/common/src/main/java/com/github/khanshoaib3/minecraft_access/mixin/InGameHudMixin.java#L28-L34

I'd like to help in fixing this, can you please explain more about this comment?

**Comment by khanshoaib3** [comment]
That's for a config option to toggle speaking the held item, I now doubt that it should be toggleable.

**Comment by boholder** [comment]
> I now doubt that it should be toggleable.

Yeah... guess no one want to close it.
