### ISSUE TITLE
Replace mouse keys with bracket keys ("[" and "]")

### ISSUE THREAD

**Issue by boholder** [minecraft-access/minecraft-access#39]
For this TODO,
https://github.com/khanshoaib3/minecraft-access/blob/86b33fb1a372d512e10eb9fd651a0508c52904bc/common/src/main/java/com/github/khanshoaib3/minecraft_access/MainClass.java#L89-L95

I directly modified the key-binding (set the `Attack/Destory` button to the `[` key) and this setting can coexist with our custom left mouse key simulation (for inventory operation AFAIK). We can press `[` to perform attack in world when no GUI window is opened.

https://github.com/khanshoaib3/minecraft-access/blob/86b33fb1a372d512e10eb9fd651a0508c52904bc/common/src/main/java/com/github/khanshoaib3/minecraft_access/utils/KeyBindingsHandler.java#L84-L90

That has satisfied this TODO.

But I found out that we can't apply this with the right mouse key. Set the `User Item/Place Block` button to the `]` key doesn't work. Our right mouse key simulation still works under this situation, but we can't place blocks in world with newly set `]` key.
Maybe we should make the right key works as well.

**Comment by khanshoaib3** [comment]
Mapping the mouse keys to brackets by default would be a good choice and it will make it more streamlined with the menu keys. Will see about it.

**Comment by boholder** [comment]
Since some users will still using their mouse when playing, directly unregister the mouse keys (in game settings) (at mod initialization stage) is not a good idea, it will left only one side works, either keyboard keys or mouse keys.

We need to make **both** of them work **at the same time**.

Here is an idea: we can listening the `[` and `]` key pressing and simulate the `mouse left` and `mouse right` key pressing, maybe make a new `net.minecraft` mixin and invoke two methods. I don't know which method in which class should be invoked, Let's find out that.

**Comment by boholder** [comment]
~~`KeyBinding.onKeyPressed` with `GLFW.GLFW_MOUSE_BUTTON_*` could simulate mouse keys pressing.~~ No, it couldn't trigger attack when holding a weapon, it could trigger block destroy and item using.

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/modification-development/2693786-solved-minecraft-modding-key-binding-click

**Comment by boholder** [comment]
I wonder if we can directly invoke classes under `org.lwjgl.glfw` to achieve mouse moving and clicking simulation.
I've checked yarn code and asked four times in Fabric Discord but have no answer yet.

**Comment by boholder** [comment]
The current conclusion:

1. If we just want to map two custom keys on keyboard onto left and right mouse keys, it's easy to be implemented, as we already have the `MouseUtils`.
2. But If we want to map two keys on vanilla `Attack` and `Use` keys, I haven't found the solution for now.

I think we can just implement the plan one and remind users keep their `Attack` and `Use` keys on default mouse keys. It can also achieve the goal that make both of them work at the same time.
