### ISSUE TITLE
Update package name

### ISSUE THREAD

**Issue by sgmedev** [minecraft-access/minecraft-access#401]
The current package name `com.github.khanshoaib3.minecraft_access` is no longer valid since we have moved to an org, it should be renamed to `io.github.minecraft_access.minecraft_access`. This should not be a breaking change since we do not currently expose any Java API.

**Comment by boholder** [comment]
I'm sorry... but I highly against this change, it requires to change directories names, which will overwrite all the lines in git, so we can't (easily) track back with `git blame`.

**Comment by BrailleBennett** [comment]
> lines

I believe that it won't overwrite it if git recognizes that it's a move and not a delete/recreation.

**Comment by boholder** [comment]
> > lines
> 
> I believe that it won't overwrite it if git recognizes that it's a move and not a delete/recreation.

Sure, I'll test it locally soon.

**Comment by boholder** [comment]
@BrailleBennett @TheSuperGamer20578 Yeah, git does know and won't mess up blame command, now I approve this issue.

**Comment by sgmedev** [comment]
Now that we own `mcaccess.org`, the package name should be something like `org.mcaccess.minecraftaccess` or `org.mcaccess.mod`.

**Comment by boholder** [comment]
> Now that we own `mcaccess.org`, the package name should be something like `org.mcaccess.minecraftaccess` or `org.mcaccess.mod`.

I'd prefer a short one like `org.mcaccess.mod`.
Or should we rename organization and repo?...

**Comment by boholder** [comment]
> Now that we own `mcaccess.org`, the package name should be something like `org.mcaccess.minecraftaccess` or `org.mcaccess.mod`.

I'd prefer a short one like `org.mcaccess.mod`.
Or should we rename organization and repo?...
