### ISSUE TITLE
Add key binding to Narrator Menu opeartions

### ISSUE THREAD

**Issue by boholder** [minecraft-access/minecraft-access#41]
That's not a bad idea IMO, there are some operations will be frequently executed in a short period, `Block and fluid target information` `Light level` `Find water` for example. Currently executing one operation will require pressing `Tab` multiple times.
I'll working on it first when I get some time.

**Comment by khanshoaib3** [comment]
Yeah. I was thinking of a combination with the f4 key, like f4 + 1 would trigger the first option in the f4 menu and f4 + 2 would trigger the second and so on.

**Comment by boholder** [comment]
Working on it. Most of new code are put in `NarratorMenu`. There is no need to register new keys in `KeyBindingsHandler` to implement functions such as the `F3 + key`. But I think registering these functions as configurable keys and leave them as it for user's flavor is also an option, what do you think? @khanshoaib3

**Comment by boholder** [comment]
I come up with a better key binding, reserve key `B` for this.

* Press `F4 + B` you can loop switch functions in narrator menu.
* Then press the single key `B` to trigger it once.
* Repeat pressing key `B` to trigger the selected function again and again.

The reasons why I discard two-key-combing design:

1. It will require one hand totally leave its position to press double keys at the same time, you will either can't move with `wsad` or can't rotating with `ikjl`. For example, I want to check if all blocks inside my room has light level above 7 to prevent monster spawning, I'd like to trigger `light level narrating` while move around.

2. it seems that `F4 + number key` will trigger both my custom function and vanilla `hotbar item selection switch`. I can't find a way to prevent that.

And I'll improve the narrator menu with original idea: add number keys on each function, such as `1. Block and Fluid target information`, `2. Light Level`, then you can trigger that function WITHIN narrator menu with corresponding number key. It's better than previous pressing multiple `tab` key to select desried function then press `enter` to trigger that.

What does it sounds like to you? @khanshoaib3
