### ISSUE TITLE
Marked POI Scan Button

### ISSUE THREAD

**Issue by boholder** [minecraft-access/minecraft-access#43]
Press `Enable Key` to indicate a/an block/entity through crosshair (similar to POI locking) and let the mod continually scan surroundings and report the targets location (similar to fluid detection). Stop the scanning by pressing `Alt` + `Enable Key`.

One thing I'm concerned about is that I remember fluid detection causing a brief lag (about seconds) (default range is 10 blocks). But this is basically a simple BFS algorithm and I can't find any room for optimization.
I don't know if MC allows us to create our own thread pools so we can put this logic in a thread pool. And I don't think it's a good idea to manage threads manually either.

**Comment by khanshoaib3** [comment]
I'm confused, is this feature supposed to find a similar crosshair block in the area??

I too wanted to make things a little efficient, especially for poi blocks algorithm. The earlier implementation used threads but that causing a "Concurrent" error. Guess we can't do traditional threading.

**Comment by boholder** [comment]
> I'm confused, is this feature supposed to find a similar crosshair block in the area??

Yep, Trix want to check floating logs in Discord, you've seen his/her message.
After "lock" a type of block you can move around to find it, without staring at that block.

**Comment by boholder** [comment]
This feature is for providing a custom POI selection outside of hard-coded, and can be convenient for players to find a specific type of POI when the surrounding has a large number of different types of POIs (for example, in a mixed captive area in which contains different types of animals).

Design changes: 
* Allows targeting on blocks or entities, in `Block` or `Entity` format.
* **Will suppress** other POIs detecting and reporting (in sound effect and location reporting) while this feature is enabled.

Use `Control` + `Locking Key (Y)` to trigger the mark, press `Control` + `Alt` + `Locking Key (Y)` to cancel the mark. This function should be triggered less often and should not be triggered by mistake, so the buttons are intentionally set to be more complex.
