### ISSUE TITLE
1.20 Update

### ISSUE THREAD

**Issue by khanshoaib3** [minecraft-access/minecraft-access#60]
Update the mod to support minecraft 1.20.x

**Comment by khanshoaib3** [comment]
Affected and working features-
- [x] Fluid Detector 
- [x] Read Crosshair - Regular signs and hanging signs 
- [x] Inventory Controls - Deselect/Unfocus Text fields. Thanks to @boholder it works now!
- [x] Time of Day
- [x] POI Blocks Locking  - ~absolute positions for blocks like levers, comparator, buttons, etc. are not taken into account because the `new BlockPos()` now takes `Vec3i` instead of `Vec3d`. So now the locking feature locks on to the center of every block~ Works! Thanks to @boholder 
- [x] Recipe section buttons
- [x] Book screen
- [x] Book edit screen

**Comment by boholder** [comment]
I'm not sure which part of code is corresponding to `Inventory Controls - Deselect/Unfocus Text fields` inside `InventoryControls.class`...... Did you mean these code:
https://github.com/khanshoaib3/minecraft-access/blob/f615c30e3e6d80f200277d0489e8b2dcdd872b68/common/src/main/java/com/github/khanshoaib3/minecraft_access/features/inventory_controls/InventoryControls.java#L177-L214

**Comment by khanshoaib3** [comment]
Yup, these are the ones and I should've replied earlier, I don't know how I missed your message.

**Comment by boholder** [comment]
> Yup, these are the ones and I should've replied earlier, I don't know how I missed your message.

Maybe that's because I didn't quote your reply, I don't know.
